ndokter/dsmr_parser

- CHANGELOG.rst
- README.rst
- dsmr_parser/serial.py
- setup.py
I added a reader implementation using asyncio so telegrams can be received without IO blocking.
I wanted to keep it a generator in spirit of the original reader. But was not able to create it that way. Async generators are only supported as of Python 3.6. 
The current implementation uses a passed in asyncio.Queue object to push messages out.
Would you be so kind to release this change so I can finish my integration with home-assistant?
> Add asyncio reader.

- dsmr_parser/serial.py
https://github.com/ndokter/dsmr_parser/issues/4
> Even parity offers better compatibility for v2.2.

- dsmr_parser/__main__.py
- dsmr_parser/protocol.py
This allows connections with TCP for example `ser2net`, `p1-wifi gateway` or when proxying from a RPi using `socat`: 
socat /dev/ttyUSB0,b9600 TCP-LISTEN:1234,reuseaddr
> Add support for TCP connections

- dsmr_parser/protocol.py
This PR will solve CRC issues for me when using the DSMRProtocol class. It effectively adds line feeds again after they've been stripped by split.
> Pass lines to parser including line endings

- dsmr_parser/clients/protocol.py
This will allow support for: https://github.com/home-assistant/home-assistant/pull/7535
Currently i'm assuming V5 serial settings are equal to V4. I will ask users to test.
> Add DSMR5 option to protocol.

- dsmr_parser/parsers.py
This PR fixes #24 and adds support for optional signatures like the *_L2_* and *_L3_* ones (i.e. VOLTAGE_SAG_L2_COUNT). It just parses the ones that are present in the telegram data and doesn't care about missing ones.
> Support optional telegram signatures

- dsmr_parser/clients/telegram_buffer.py
Some smart meters can return 00 0D 0A after the checksum instead of just 0D 0A.
> Optional NUL after checksum

- dsmr_parser/obis_references.py
- dsmr_parser/telegram_specifications.py
I've added the 1.8.0 OBIS reference to the total imported electricity, i found a reference to it in this document https://www.bundesnetzagentur.de/DE/Service-Funktionen/Beschlusskammern/Beschlusskammer6/BK6_31_GPKE_und_GeLiGas/Mitteilung_Nr_20/Anlagen/Obis-Kennzahlen-System_2.0.pdf?__blob=publicationFile&v=2
ELECTRICITY_IMPORTED_TOTAL = r'\d-\d:1\.8\.0.+?\r\n'
and
obis.ELECTRICITY_IMPORTED_TOTAL: CosemParser(ValueParser(Decimal)),
This change allows the parser to read the Luxemburgish Electricity Smartmeter Value.
> Lux-creos-obis-1.8.0

- dsmr_parser/clients/__init__.py
- dsmr_parser/clients/settings.py
The serial settings for DSMR v5.0 are 115200 8N1 (see page 15 of https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf). Tested with a Sagemcom XS210.
> Add serial settings for DSMR v5.0

- dsmr_parser/clients/serial_.py
The CPU load of running a DSMR v5.0 client is around 10% for me on a Raspberry PI 3B. I ran a profiler to find out where all this time is spent. Since it turns out that it is somewhat expensive to read from the serial port, I tried to optimise this a bit. Reading out larger chunks of data helps performance significantly. I saw the CPU load drop by at least 50%.
See also pyserial/pyserial#216 and pyserial/pyserial#318.
> Improve performance: read more data from serial port at once

- CHANGELOG.rst
- dsmr_parser/objects.py
- setup.py
hi Nigel,
I reconsidered adding a value property to GenericProfileObject and dropped the idea.
Instead I added a to_json() method to all objects, so the objects can serialize themselves now to json. This solves my issue.
I would appreciate if you merge and release it.
Usage is simple:
```python
from dsmr_parser import telegram_specifications
from dsmr_parser.objects import Telegram
from dsmr_parser.parsers import TelegramParser
from example_telegrams import TELEGRAM_V4_2
parser = TelegramParser(telegram_specifications.V4)
telegram = Telegram(TELEGRAM_V4_2, parser, telegram_specifications.V4)
json_representation = telegram.to_json()
print(json.dumps(json.loads(json_representation), indent=4))
```
```output
{
"P1_MESSAGE_HEADER": {
"value": "42",
"unit": null
},
"P1_MESSAGE_TIMESTAMP": { …
```
> Fix json serialization

- dsmr_parser/clients/protocol.py
- dsmr_parser/obis_references.py
- dsmr_parser/telegram_specifications.py
The Smarty meter (Luxembourg) is using a different OBIS reference for equipment identifier compared to Dutch and Belgian meters (see https://smarty.creos.net/wp-content/uploads/P1PortSpecification.pdf).
Add the OBIS reference for Smarty and also enable to set `dsmr_version` to `5L` for Luxembourg meters.
> Add Luxembourg equipment identifier

- dsmr_parser/parsers.py
With an iskra m550 I got the following exception:
```python
Failed to parse telegram: ("Invalid '%s' line for '%s'", '99.97.0()\r\n', <dsmr_parser.parsers.ProfileGenericParser object at 0x76814210>)
```
This is caused by empty parentheses `()`, which can't be handled by `ProfileGenericParser`. 
This fixes the issue for me: 
* make sure the `_is_line_wellformed` function returns true if there are empty parentheses; 
* if  `_is_line_wellformed`  returns `true`, the empty value will be turned into `None`
* since ` _parse_values` can't handle None values, I also added a check in `_parse_values`  ; if `None` is the case, call the parent function
> fix for empty parentheses in ProfileGenericParser

- dsmr_parser/__main__.py
- dsmr_parser/clients/protocol.py
- test/test_protocol.py
* Since dsmr-parser is listen-only, it will not notice interrupted connections
and DSMR device restarts. The connection will be reset after an (optional)
keep-alive interval if no messages were received from the device.
> Optional keep alive monitoring for TCP/IP connections

- README.rst
- dsmr_parser/clients/protocol.py
- dsmr_parser/clients/serial_.py
- tox.ini
This PR removes the `@asyncio.coroutine` decorator and `yield from` occurrences from the codebase and replaces them with the Python 3.5 async/await syntax.
This PR causes Python 3.4 to be dropped for async serial use, adjusted the README for that.
Additionally, added Python 3.9 to tox.
closes #64
> Remove deprecated asyncio coroutine decorator

- README.rst
- dsmr_parser/clients/__init__.py
- dsmr_parser/clients/socket_.py
I added a new `SocketReader` client to enable connecting to a remote serial port. This makes it possible to run `dsmr_parser` based scripts on another machine. I tested this running `ser2net` on a single board computer connected to my Landis+Gyr E350 smart meter.
Let me know if you like it and if you require more changes to the implementation. Keep up the good work!
> Add SocketReader to connect to remote serial port

- .github/workflows/tests.yml
- README.rst
- See commits
- Python 3.10 tests seem to run fine: https://github.com/dennissiemensma/dsmr_parser/runs/6101291715?check_suite_focus=true
> Test Python 3.10 in CI + legacy badge fix

- .github/workflows/tests.yml
- Run tests for Python 3.11 as well _(they seem to pass :confetti_ball: )_
- Bump versions of Actions used in CI
- No longer run Python 3.6 in CI as it is end-of-life _([for almost a year now)](https://devguide.python.org/versions/#python-release-cycle)_
> Feature/python 3.11

- dsmr_parser/clients/serial_.py
fix inheritance of synchronous read_as_object method from parent
> asynchronous read_as_object method

- dsmr_parser/objects.py
- dsmr_parser/parsers.py
- test/test_parse_fluvius.py
- tox.ini
Add pylama back in + fix uniform style issues reported by pylama.
Should work from python 3.7 onwards, as python 3.6 is no longer supported this shall not pose problems.
> add pylama back in + fix uniform style issues reported by pylama

- dsmr_parser/value_types.py
- test/test_parse_v5.py
Sometimes the timestamp in the DSMR message is invalid (when no data read read from the mbus meter?), and then parsing fails. Fixing this by handling the exception and returning None for invalid
timestamps. Fixes: #120
> Fix parsing with invalid timestamps

- dsmr_parser/parsers.py
- test/test_parse_fluvius.py
- Same value returned for month timestamp and occurrence timestamp for BELGIUM_MAXIMUM_DEMAND_13_MONTHS.
- Fluvius meter test case was updated with assertions for all timestamps.
> Bug/duplicate index BELGIUM_MAXIMUM_DEMAND_13_MONTHS

- dsmr_parser/obis_references.py
- dsmr_parser/parsers.py
- test/test_parse_fluvius.py
- test/test_parse_iskra_ie.py
- test/test_parse_v2_2.py
- test/test_parse_v3.py
- test/test_parse_v4_2.py
- test/test_parse_v5.py
This pull req fixes 2 things:
First of all we seem to handle the exception in the code for parsing errors and just log a message.
So tests never see parsing errors. Which is not what we want :) So we raise the exception triggered by the parsing.
Next to that, we enable multiline flag on the regex, so it creates a new line after every \n.
This allows us to use line start (^) in the regexes, so we don't match things in a middle somewhere. (Fixes #128)
> Fix parsing tests and line start matching

- dsmr_parser/telegram_specifications.py
- test/test_parse_fluvius.py
When other devices are present via the WMBus, the signature for the EQUIPMENT_IDENTIFIER will match not only the ID of the meter but also the IDs of the MBus devices.
The parser will try to add every match to the telegram (`telegram.add(obis_reference, dsmr_object)`), overwriting in each attempt the previously mapped EQUIPMENT_IDENTIFIER. Eventually, only the last match which will be set as ID.
See `objects.py` line 33.
If one try to access the field as `telegram[obis.EQUIPMENT_IDENTIFIER]` the correct ID is captured. This is because the "raw" obis references are only saved for their first occurrence.
See `objects.py` lines 42-43.
This last type of access is used in `test_parse_fluvius.py` line 36, which passes:
```python
assert result[obis.EQUIPMENT_IDENTIFIER].value == …
```
> EQUIPMENT IDENTIFIER is wrong for Fluvius meters when other mbus devices are present

- dsmr_parser/obis_references.py
- dsmr_parser/telegram_specifications.py
- test/test_parse_fluvius.py
- test/test_parse_v5_eon_hungary.py
As BELGIUM_MAX_CURRENT_PER_PHASE was also used in the EON telegram. Better make it a global/non-country specific value and adjust it everywhere.
Still on the belgian meters it seems to only report a value for L1 even on a 3phase meter.
> Adjust the naming of the MAX_POWER and MAX_CURRENT obis values

- dsmr_parser/obis_references.py
- dsmr_parser/telegram_specifications.py
- test/test_parse_fluvius.py
This commit removes BELGIUM_MAX_POWER_PER_PHASE and uses ACTUAL_TRESHOLD_ELECTRICITY as this has same regex. So useless to keep the BELIUM variant.
> Remove BELGIUM_MAX_POWER_PER_PHASE

- dsmr_parser/telegram_specifications.py
to avoid negative CURRENT_ELECTRICITY_USAGE
> Q3D add CURRENT_ELECTRICITY_DELIVERY

- dsmr_parser/parsers.py
We need to create a copy of the head_parsers.
Otherwise the self.value_formats contains just a reference to head_parsers.
But the self.value_formats is modified in the _parse_values, causing invalid values in the head_parsers list.
> Copy head_parsers list on construct.

- dsmr_parser/value_types.py
Pytz will load timezone info from files in
a lazy fashion on first access. This triggers warnings in HA due to it blocking the event loop.
Pre-load the needed timezone info at module import instead, which will run in executor in HA.
Fixes #156
> Avoid loading timezone at runtime

- .github/workflows/tests.yml
Fixes warnings in CI: https://github.com/ndokter/dsmr_parser/actions/runs/9450071019
- https://github.com/actions/checkout/releases
- https://github.com/actions/setup-python/releases
- https://github.com/actions/cache/releases
- https://github.com/codecov/codecov-action/releases
> Bump Github Actions to latest versions in favor of Node deprecations

- dsmr_parser/clients/serial_.py
Possible solution for Issue #80. Instead of throwing an exception when input from serial can't be parsed, it passes the current step while the loop keeps going. This will mean one 'row' is missing from the telegram. The user should keep this in mind and not expect every telegram to be formed the same way.
Another option is to yield None, which I tried first. On second thought, it is not that helpful because there is nothing to return (though we could give the 'raw' bytestring, but that would complicate things for the user as well.
> Don't thow an error when string can't be decoded to ascii
